source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               testProjects/,\
               resources/,\
               .,\
               plugin.xml,\
               about.html
src.includes = about.html
